spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: mysecretpassword

  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: db/changelog-master.yaml
    enabled: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

